# Generated by Django 3.2 on 2021-04-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('league', models.CharField(max_length=30)),
                ('tournament_id', models.IntegerField()),
                ('match_id', models.CharField(max_length=8)),
                ('match_utc_time', models.DateTimeField()),
                ('match_status', models.CharField(max_length=3)),
                ('team', models.CharField(max_length=30)),
                ('opposition', models.CharField(max_length=30)),
                ('ft1', models.IntegerField(null=True)),
                ('ft2', models.IntegerField(null=True)),
                ('home_odds', models.DecimalField(decimal_places=3, max_digits=6)),
                ('away_odds', models.DecimalField(decimal_places=3, max_digits=6)),
                ('draw_odds', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
            ],
            options={
                'ordering': ['match_utc_time'],
            },
        ),
    ]
